### PR TITLE
Factory methods for event store and aggregate lock

### PR DESCRIPTION
**Pull request by nizachon**
Per our discussion.

### CODE REVIEW

**Comment by adrai** [comment]
Did you have already done a "real-life" check in your project?

**Comment by nizachon** [comment]
That's #1 on my list for today! :-)

**Comment by nizachon** [comment]
Just to make sure: were you asking if we had already re-implemented our adapter as an *event store* instead of a *store*, or ...?

**Comment by adrai** [comment]
Just to be sure you tested your branch (pull request) on you real-live system



Il giorno 6-mar-2015, alle ore 17:36, nizachon <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Just to make sure: were you asking if we had already re-implemented our adapter as an event store instead of a store, or ...?

-

**Comment by nizachon** [comment]
Works as expected.

**Pull request merged**
